In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a)
print(a.ndim, a.shape, a.dtype )

[[1. 2. 3.]
 [4. 5. 6.]]
2 (2, 3) float32


In [5]:
b = np.ones((3,4))
print(b)

c = np.zeros((3,3))
print(c)

d = np.eye(3)
print(d)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
f = np.random.random((2,2))
print(f)

g = np.random.randint(0,10,(3,3))
print(g)

j = np.random.normal(0,1,(3,3))
print(j)
print(j.mean(), j.var(), j.std())

[[0.13176092 0.64319773]
 [0.03472609 0.52973709]]
[[1 0 3]
 [5 0 5]
 [8 7 6]]
[[ 0.32145451 -1.02288297 -1.98186431]
 [-0.43692064 -1.65891435 -0.58620824]
 [-0.90795149  0.90569056  0.00987461]]
-0.5953024802697232 0.7576920789609081 0.8704550987620833


In [9]:
A = np.ones((2,3))
B = np.ones((2,3))
C = A + B
print(C)

[[2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
d = np.array([[1,2,3],[4,5,6]])
print(d)
print(d.shape)

d = d.reshape((3,2))
print(d)

# d = d.reshape((3,3))   # ERROR because total number of elements do not match
# print(d)

d = d.flatten()
print(d)
print(d.shape)
d = d.reshape((1,-1))
print(d)
print(d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
(6,)
[[1 2 3 4 5 6]]
(1, 6)


In [19]:
v = np.random.randint(0,10,(3,4))
print(v)

v_t = v.T
print(v_t)

[[6 7 1 3]
 [4 2 8 2]
 [9 4 3 2]]
[[6 4 9]
 [7 2 4]
 [1 8 3]
 [3 2 2]]


# Arithmetic Operations using matrcies

In [20]:
# Arithmetic Operations using matrcies
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [25]:
# Matrix Multiplication
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x.shape, y.shape)
z = x.dot(y)
print(z)

(2, 2) (2, 2)
[[19 22]
 [43 50]]


In [27]:
# Logical Operations
print(z > 20)
print(z[z > 20])

[[False  True]
 [ True  True]]
[22 43 50]


In [28]:
# Scalar Operations
print(z)
print(z + 10)

[[19 22]
 [43 50]]
[[29 32]
 [53 60]]


In [30]:
# Mathematical Functions
print(np.sin(z))
print(np.cos(z))
print(np.tan(z))

print(np.log(z))
print(np.exp(z))
print(np.sqrt(z))

[[ 0.14987721 -0.00885131]
 [-0.83177474 -0.26237485]]
[[ 0.98870462 -0.99996083]
 [ 0.5551133   0.96496603]]
[[ 0.15158947  0.00885166]
 [-1.49838734 -0.27190061]]
[[2.94443898 3.09104245]
 [3.76120012 3.91202301]]
[[1.78482301e+08 3.58491285e+09]
 [4.72783947e+18 5.18470553e+21]]
[[4.35889894 4.69041576]
 [6.55743852 7.07106781]]


# Slicing

In [33]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

# Slicing
print(A[0, :])   # First Row
print(A[:, 0])   # First Column
print(A[1, 1])   # Element at Second Row, Second Column

print(A[A > 5])   # Elements greater than 5

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 4 7]
5
[6 7 8 9]


# Broadcasting

In [39]:
A = np.random.randint(0,10,(5,5,3))
print(A.shape)

B = np.array([10,-10,10])
print(B.shape)

C = A + B
print(C)
print(C.shape)


(5, 5, 3)
(3,)
[[[ 13  -9  11]
  [ 12  -9  19]
  [ 16  -2  17]
  [ 16  -5  15]
  [ 14  -3  12]]

 [[ 13  -2  19]
  [ 13  -2  12]
  [ 16  -2  11]
  [ 15 -10  11]
  [ 19  -4  13]]

 [[ 16  -3  12]
  [ 13  -6  12]
  [ 11  -4  16]
  [ 13  -7  15]
  [ 17  -6  15]]

 [[ 13  -5  18]
  [ 12  -1  15]
  [ 19  -7  13]
  [ 18  -5  18]
  [ 17 -10  16]]

 [[ 15  -2  18]
  [ 16  -4  17]
  [ 18  -1  14]
  [ 16  -7  10]
  [ 14  -6  16]]]
(5, 5, 3)
